// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnjhegebwoutslqoishb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuamhlZ2Vid291dHNscW9pc2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzQxNzQsImV4cCI6MjA3MDE1MDE3NH0.CzjyUuTkcWgu-vaBXc2kkHBszbFcjRk3fEiTxz93X8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});